import type { Deal, Product, Review, Shop, User } from "@/types";

const img = (id: string, width = 900) => {
  void id;
  void width;
  return undefined;
};

export const users: User[] = [
  {
    id: "user-alina",
    email: "alina@example.test",
    username: "alina.archive",
    firstName: "Алина",
    lastName: "Соколова",
    displayName: "Alina Archive",
    emoji: "✦",
    avatarUrl: img("photo-1494790108377-be9c29b29330", 320),
    coverUrl: img("photo-1515886657613-9f3515b0c78f", 1400),
    bio: "Собираю тихий luxury, люблю аккуратные силуэты и честные описания состояния.",
    city: "Москва",
    rating: 4.9,
    reviewsCount: 42,
    salesCount: 119,
    purchasesCount: 28,
    listingsCount: 16,
    favoritesCount: 74,
    verified: true,
    roles: ["USER", "SELLER"],
    createdAt: "2025-09-18T10:00:00.000Z",
    customization: {
      nicknameColor: "#D9FF43",
      avatarFrame: "lime",
      emoji: "✦",
      coverStyle: "static",
    },
  },
  {
    id: "user-mark",
    email: "mark@example.test",
    username: "mark.layers",
    firstName: "Марк",
    lastName: "Орлов",
    displayName: "Mark Layers",
    emoji: "◆",
    avatarUrl: img("photo-1500648767791-00dcc994a43e", 320),
    coverUrl: img("photo-1503342217505-b0a15ec3261c", 1400),
    bio: "Техничные куртки, винтажные кроссовки и редкие капсулы без лишнего шума.",
    city: "Санкт-Петербург",
    rating: 4.8,
    reviewsCount: 31,
    salesCount: 86,
    purchasesCount: 44,
    listingsCount: 12,
    favoritesCount: 53,
    verified: true,
    roles: ["USER", "SELLER"],
    createdAt: "2025-11-03T10:00:00.000Z",
    customization: {
      nicknameColor: "#F4F0E8",
      avatarFrame: "graphite",
      emoji: "◆",
      coverStyle: "static",
    },
  },
  {
    id: "user-lera",
    username: "lera.vault",
    firstName: "Лера",
    lastName: "Минаева",
    displayName: "Lera Vault",
    emoji: "●",
    avatarUrl: img("photo-1517841905240-472988babdf9", 320),
    coverUrl: img("photo-1487222477894-8943e31ef7b2", 1400),
    bio: "Покупаю вещи с историей и продаю только то, что сама бы носила.",
    city: "Казань",
    rating: 4.7,
    reviewsCount: 19,
    salesCount: 37,
    purchasesCount: 62,
    listingsCount: 7,
    favoritesCount: 91,
    verified: false,
    roles: ["USER"],
    createdAt: "2026-01-14T10:00:00.000Z",
    customization: {
      nicknameColor: "#CFCAC0",
      avatarFrame: "silver",
      emoji: "●",
      coverStyle: "animated-coming-soon",
    },
  },
  {
    id: "user-roma",
    username: "roma.sizes",
    firstName: "Роман",
    lastName: "Беляев",
    displayName: "Roma Sizes",
    emoji: "◇",
    avatarUrl: img("photo-1506794778202-cad84cf45f1d", 320),
    coverUrl: img("photo-1496747611176-843222e1e57c", 1400),
    bio: "Ищу идеальные посадки, сохраняю чеки и всегда показываю детали перед встречей.",
    city: "Екатеринбург",
    rating: 4.6,
    reviewsCount: 17,
    salesCount: 24,
    purchasesCount: 35,
    listingsCount: 5,
    favoritesCount: 28,
    verified: false,
    roles: ["USER"],
    createdAt: "2026-02-07T10:00:00.000Z",
    customization: {
      nicknameColor: "#EAE6DA",
      avatarFrame: "none",
      emoji: "◇",
      coverStyle: "static",
    },
  },
  {
    id: "user-daniil",
    username: "daniil.scan",
    firstName: "Даниил",
    lastName: "Громов",
    displayName: "Daniil Scan",
    emoji: "✶",
    avatarUrl: img("photo-1519085360753-af0119f7cbe7", 320),
    coverUrl: img("photo-1495385794356-15371f348c31", 1400),
    bio: "Проверяю фурнитуру, ярлыки и состояние. Предпочитаю личные сделки.",
    city: "Новосибирск",
    rating: 4.8,
    reviewsCount: 27,
    salesCount: 61,
    purchasesCount: 21,
    listingsCount: 9,
    favoritesCount: 39,
    verified: true,
    roles: ["USER", "SELLER"],
    createdAt: "2025-08-26T10:00:00.000Z",
    customization: {
      nicknameColor: "#D9FF43",
      avatarFrame: "lime",
      emoji: "✶",
      coverStyle: "static",
    },
  },
];

export const shops: Shop[] = [
  {
    id: "shop-asphalt",
    ownerId: "user-mark",
    name: "Asphalt Archive",
    slug: "asphalt-archive",
    avatarUrl: img("photo-1515886657613-9f3515b0c78f", 400),
    coverUrl: img("photo-1529139574466-a303027c1d8b", 1600),
    description:
      "Техничная верхняя одежда, спокойные оттенки и вещи, которые выдерживают город.",
    rating: 4.9,
    reviewsCount: 88,
    verified: true,
    salesCount: 312,
    listingsCount: 38,
    createdAt: "2025-08-20T10:00:00.000Z",
  },
  {
    id: "shop-lime",
    ownerId: "user-alina",
    name: "Lime Line",
    slug: "lime-line",
    avatarUrl: img("photo-1496747611176-843222e1e57c", 400),
    coverUrl: img("photo-1487222477894-8943e31ef7b2", 1600),
    description:
      "Подборка ярких аксессуаров, сумок и statement-вещей без перегруза.",
    rating: 4.8,
    reviewsCount: 64,
    verified: true,
    salesCount: 224,
    listingsCount: 25,
    createdAt: "2025-10-02T10:00:00.000Z",
  },
  {
    id: "shop-mono",
    ownerId: "user-daniil",
    name: "Mono Stock",
    slug: "mono-stock",
    avatarUrl: img("photo-1503341455253-b2e723bb3dbb", 400),
    coverUrl: img("photo-1503342217505-b0a15ec3261c", 1600),
    description:
      "Черная база, минимализм, Rick Owens и вещи с сильным силуэтом.",
    rating: 4.7,
    reviewsCount: 41,
    verified: true,
    salesCount: 156,
    listingsCount: 18,
    createdAt: "2025-12-12T10:00:00.000Z",
  },
  {
    id: "shop-north",
    ownerId: "user-roma",
    name: "North Vault",
    slug: "north-vault",
    avatarUrl: img("photo-1523398002811-999ca8dec234", 400),
    coverUrl: img("photo-1496747611176-843222e1e57c", 1600),
    description:
      "Outdoor, The North Face, Moncler и городские куртки для плохой погоды.",
    rating: 4.6,
    reviewsCount: 35,
    verified: false,
    salesCount: 98,
    listingsCount: 20,
    createdAt: "2026-01-19T10:00:00.000Z",
  },
  {
    id: "shop-rick",
    ownerId: "user-mark",
    name: "Rick Room",
    slug: "rick-room",
    avatarUrl: img("photo-1495385794356-15371f348c31", 400),
    coverUrl: img("photo-1529139574466-a303027c1d8b", 1600),
    description:
      "Длинные линии, плотный хлопок, обувь и аксессуары для темного гардероба.",
    rating: 4.9,
    reviewsCount: 52,
    verified: true,
    salesCount: 171,
    listingsCount: 14,
    createdAt: "2025-07-29T10:00:00.000Z",
  },
  {
    id: "shop-luxe",
    ownerId: "user-lera",
    name: "Luxe Repeat",
    slug: "luxe-repeat",
    avatarUrl: img("photo-1487222477894-8943e31ef7b2", 400),
    coverUrl: img("photo-1509631179647-0177331693ae", 1600),
    description:
      "Louis Vuitton, Gucci, аккуратные сумки и аксессуары с прозрачным состоянием.",
    rating: 4.7,
    reviewsCount: 48,
    verified: true,
    salesCount: 143,
    listingsCount: 17,
    createdAt: "2025-09-05T10:00:00.000Z",
  },
  {
    id: "shop-sneaker",
    ownerId: "user-daniil",
    name: "Sneaker Sreda",
    slug: "sneaker-sreda",
    avatarUrl: img("photo-1542291026-7eec264c27ff", 400),
    coverUrl: img("photo-1491553895911-0055eca6402d", 1600),
    description:
      "Кроссовки, редкие размеры и честные фото подошвы, коробки и ярлыков.",
    rating: 4.8,
    reviewsCount: 73,
    verified: true,
    salesCount: 201,
    listingsCount: 31,
    createdAt: "2025-06-15T10:00:00.000Z",
  },
];

export const products: Product[] = [
  {
    id: "p-001",
    sellerId: "user-mark",
    shopId: "shop-asphalt",
    title: "Stone Island Shadow Project Nylon Jacket",
    slug: "stone-island-shadow-project-nylon-jacket",
    brand: "Stone Island",
    category: "куртки",
    clothingSize: "L",
    priceKopecks: 6800000,
    condition: "EXCELLENT",
    authenticityType: "ORIGINAL",
    city: "Москва",
    description:
      "Легкая техническая куртка с плотной фактурой, скрытыми карманами и чистой фурнитурой. Бирки на месте.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT", "SAFE_DEAL"],
    images: [
      { id: "p-001-1", url: img("photo-1523398002811-999ca8dec234"), alt: "Темная техническая куртка" },
      { id: "p-001-2", url: img("photo-1515886657613-9f3515b0c78f"), alt: "Фактура ткани куртки" },
    ],
    popularityScore: 96,
    createdAt: "2026-07-07T11:00:00.000Z",
  },
  {
    id: "p-002",
    sellerId: "user-alina",
    shopId: "shop-lime",
    title: "Gucci Horsebit Mini Bag",
    slug: "gucci-horsebit-mini-bag",
    brand: "Gucci",
    category: "сумки",
    priceKopecks: 9200000,
    condition: "EXCELLENT",
    authenticityType: "ORIGINAL",
    city: "Санкт-Петербург",
    description:
      "Мини-сумка в хорошем состоянии, фурнитура без сильных потертостей, есть пыльник и коробка.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT"],
    images: [
      { id: "p-002-1", url: img("photo-1594223274512-ad4803739b7c"), alt: "Черная сумка Gucci" },
      { id: "p-002-2", url: img("photo-1584917865442-de89df76afd3"), alt: "Деталь сумки" },
    ],
    popularityScore: 90,
    createdAt: "2026-07-06T12:00:00.000Z",
  },
  {
    id: "p-003",
    sellerId: "user-daniil",
    shopId: "shop-sneaker",
    title: "Nike Air Max 95 Neon",
    slug: "nike-air-max-95-neon",
    brand: "Nike",
    category: "кроссовки",
    shoeSize: "43",
    priceKopecks: 2450000,
    condition: "GOOD",
    authenticityType: "ORIGINAL",
    city: "Казань",
    description:
      "Классическая расцветка, есть следы носки на подошве. Верх чистый, без разрывов.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT", "SAFE_DEAL"],
    images: [
      { id: "p-003-1", url: img("photo-1542291026-7eec264c27ff"), alt: "Кроссовки Nike Air Max" },
      { id: "p-003-2", url: img("photo-1491553895911-0055eca6402d"), alt: "Кроссовки сбоку" },
    ],
    popularityScore: 88,
    createdAt: "2026-07-05T13:00:00.000Z",
  },
  {
    id: "p-004",
    sellerId: "user-mark",
    shopId: "shop-mono",
    title: "Rick Owens DRKSHDW Jumbo Hoodie",
    slug: "rick-owens-drkshdw-jumbo-hoodie",
    brand: "Rick Owens",
    category: "худи",
    clothingSize: "M",
    priceKopecks: 5100000,
    condition: "EXCELLENT",
    authenticityType: "ORIGINAL",
    city: "Москва",
    description:
      "Объемное худи из плотного хлопка. Силуэт оверсайз, без пятен и растяжений.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "SAFE_DEAL"],
    images: [
      { id: "p-004-1", url: img("photo-1503342217505-b0a15ec3261c"), alt: "Черное худи Rick Owens" },
      { id: "p-004-2", url: img("photo-1495385794356-15371f348c31"), alt: "Темный силуэт худи" },
    ],
    popularityScore: 92,
    createdAt: "2026-07-04T14:00:00.000Z",
  },
  {
    id: "p-005",
    sellerId: "user-lera",
    shopId: "shop-luxe",
    title: "Louis Vuitton Monogram Belt",
    slug: "louis-vuitton-monogram-belt",
    brand: "Louis Vuitton",
    category: "аксессуары",
    clothingSize: "M",
    priceKopecks: 3800000,
    condition: "GOOD",
    authenticityType: "ORIGINAL",
    city: "Сочи",
    description:
      "Ремень с мягкой патиной, есть легкие заломы на коже. Номер и фурнитура читаются.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT"],
    images: [
      { id: "p-005-1", url: img("photo-1606760227091-3dd870d97f1d"), alt: "Ремень Louis Vuitton" },
      { id: "p-005-2", url: img("photo-1601924994987-69e26d50dc26"), alt: "Детали аксессуара" },
    ],
    popularityScore: 77,
    createdAt: "2026-07-03T15:00:00.000Z",
  },
  {
    id: "p-006",
    sellerId: "user-roma",
    shopId: "shop-north",
    title: "The North Face 1996 Nuptse",
    slug: "the-north-face-1996-nuptse",
    brand: "The North Face",
    category: "куртки",
    clothingSize: "XL",
    priceKopecks: 3200000,
    condition: "GOOD",
    authenticityType: "ORIGINAL",
    city: "Екатеринбург",
    description:
      "Пух держит объем, молнии работают мягко. Есть небольшие следы носки на манжетах.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT", "SAFE_DEAL"],
    images: [
      { id: "p-006-1", url: img("photo-1515886657613-9f3515b0c78f"), alt: "Пуховая куртка The North Face" },
      { id: "p-006-2", url: img("photo-1487222477894-8943e31ef7b2"), alt: "Куртка на модели" },
    ],
    popularityScore: 83,
    createdAt: "2026-07-02T16:00:00.000Z",
  },
  {
    id: "p-007",
    sellerId: "user-alina",
    shopId: "shop-lime",
    title: "Balenciaga Wide Leg Denim",
    slug: "balenciaga-wide-leg-denim",
    brand: "Balenciaga",
    category: "брюки",
    clothingSize: "S",
    priceKopecks: 4700000,
    condition: "EXCELLENT",
    authenticityType: "ORIGINAL",
    city: "Москва",
    description:
      "Широкие джинсы с чистым низом и плотной посадкой. Размер ближе к S/M.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT"],
    images: [
      { id: "p-007-1", url: img("photo-1541099649105-f69ad21f3246"), alt: "Широкие джинсы" },
      { id: "p-007-2", url: img("photo-1475180098004-ca77a66827be"), alt: "Деним крупным планом" },
    ],
    popularityScore: 75,
    createdAt: "2026-07-01T17:00:00.000Z",
  },
  {
    id: "p-008",
    sellerId: "user-daniil",
    shopId: "shop-asphalt",
    title: "CP Company Lens Sweatshirt",
    slug: "cp-company-lens-sweatshirt",
    brand: "CP Company",
    category: "худи",
    clothingSize: "L",
    priceKopecks: 2100000,
    condition: "EXCELLENT",
    authenticityType: "ORIGINAL",
    city: "Санкт-Петербург",
    description:
      "Свитшот с линзой, плотный футер, цвет без выгорания. Документы от ресейл-магазина.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT", "SAFE_DEAL"],
    images: [
      { id: "p-008-1", url: img("photo-1529139574466-a303027c1d8b"), alt: "Свитшот CP Company" },
      { id: "p-008-2", url: img("photo-1503341455253-b2e723bb3dbb"), alt: "Деталь рукава" },
    ],
    popularityScore: 72,
    createdAt: "2026-06-30T10:00:00.000Z",
  },
  {
    id: "p-009",
    sellerId: "user-mark",
    shopId: "shop-rick",
    title: "Rick Owens Geobasket Replica Pair",
    slug: "rick-owens-geobasket-replica-pair",
    brand: "Rick Owens",
    category: "кроссовки",
    shoeSize: "42",
    priceKopecks: 1650000,
    condition: "GOOD",
    authenticityType: "REPLICA",
    city: "Москва",
    description:
      "Качественная replica-пара для образов, честно маркируется как Replica. Есть потертости на носках.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT"],
    images: [
      { id: "p-009-1", url: img("photo-1460353581641-37baddab0fa2"), alt: "Высокие кроссовки Rick Owens" },
      { id: "p-009-2", url: img("photo-1491553895911-0055eca6402d"), alt: "Пара кроссовок" },
    ],
    popularityScore: 64,
    createdAt: "2026-06-29T10:00:00.000Z",
  },
  {
    id: "p-010",
    sellerId: "user-lera",
    shopId: "shop-luxe",
    title: "Moncler Maya Down Jacket",
    slug: "moncler-maya-down-jacket",
    brand: "Moncler",
    category: "куртки",
    clothingSize: "M",
    priceKopecks: 7800000,
    condition: "EXCELLENT",
    authenticityType: "ORIGINAL",
    city: "Казань",
    description:
      "Пуховик с чистой фурнитурой и QR-ярлыком. Без дыр и заметного блеска на ткани.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "SAFE_DEAL"],
    images: [
      { id: "p-010-1", url: img("photo-1548126032-079a0fb0099d"), alt: "Пуховик Moncler" },
      { id: "p-010-2", url: img("photo-1515886657613-9f3515b0c78f"), alt: "Темная куртка" },
    ],
    popularityScore: 93,
    createdAt: "2026-06-28T10:00:00.000Z",
  },
  {
    id: "p-011",
    sellerId: "user-alina",
    title: "Supreme Box Logo Tee",
    slug: "supreme-box-logo-tee",
    brand: "Supreme",
    category: "футболки",
    clothingSize: "M",
    priceKopecks: 1900000,
    condition: "GOOD",
    authenticityType: "ORIGINAL",
    city: "Новосибирск",
    description:
      "Футболка после аккуратной носки, принт без трещин. Фото бирок отправлю по запросу.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT"],
    images: [
      { id: "p-011-1", url: img("photo-1503341455253-b2e723bb3dbb"), alt: "Белая футболка Supreme" },
      { id: "p-011-2", url: img("photo-1521572163474-6864f9cf17ab"), alt: "Футболка на вешалке" },
    ],
    popularityScore: 69,
    createdAt: "2026-06-27T10:00:00.000Z",
  },
  {
    id: "p-012",
    sellerId: "user-mark",
    shopId: "shop-sneaker",
    title: "Nike Dunk Low Panda",
    slug: "nike-dunk-low-panda",
    brand: "Nike",
    category: "кроссовки",
    shoeSize: "40",
    priceKopecks: 1390000,
    condition: "GOOD",
    authenticityType: "ORIGINAL",
    city: "Сочи",
    description:
      "Повседневная пара, кожа без глубоких заломов. Подошва очищена перед продажей.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT", "SAFE_DEAL"],
    images: [
      { id: "p-012-1", url: img("photo-1549298916-b41d501d3772"), alt: "Nike Dunk Low" },
      { id: "p-012-2", url: img("photo-1556906781-9a412961c28c"), alt: "Белые кроссовки" },
    ],
    popularityScore: 70,
    createdAt: "2026-06-26T10:00:00.000Z",
  },
  {
    id: "p-013",
    sellerId: "user-daniil",
    shopId: "shop-asphalt",
    title: "Stone Island Cargo Pants",
    slug: "stone-island-cargo-pants",
    brand: "Stone Island",
    category: "брюки",
    clothingSize: "L",
    priceKopecks: 2950000,
    condition: "EXCELLENT",
    authenticityType: "ORIGINAL",
    city: "Екатеринбург",
    description:
      "Карго с плотной тканью и аккуратной посадкой. Патч и кнопки без повреждений.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "SAFE_DEAL"],
    images: [
      { id: "p-013-1", url: img("photo-1473966968600-fa801b869a1a"), alt: "Карго брюки Stone Island" },
      { id: "p-013-2", url: img("photo-1541099649105-f69ad21f3246"), alt: "Темные брюки" },
    ],
    popularityScore: 81,
    createdAt: "2026-06-25T10:00:00.000Z",
  },
  {
    id: "p-014",
    sellerId: "user-lera",
    shopId: "shop-lime",
    title: "Balenciaga City Bag Replica",
    slug: "balenciaga-city-bag-replica",
    brand: "Balenciaga",
    category: "сумки",
    priceKopecks: 1250000,
    condition: "GOOD",
    authenticityType: "REPLICA",
    city: "Москва",
    description:
      "Replica-сумка для стилизаций, состояние честно указано. Мягкая кожа, есть потертости на углах.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT"],
    images: [
      { id: "p-014-1", url: img("photo-1584917865442-de89df76afd3"), alt: "Сумка Balenciaga City" },
      { id: "p-014-2", url: img("photo-1594223274512-ad4803739b7c"), alt: "Черная сумка" },
    ],
    popularityScore: 58,
    createdAt: "2026-06-24T10:00:00.000Z",
  },
  {
    id: "p-015",
    sellerId: "user-mark",
    shopId: "shop-north",
    title: "The North Face Mountain Light",
    slug: "the-north-face-mountain-light",
    brand: "The North Face",
    category: "куртки",
    clothingSize: "M",
    priceKopecks: 2650000,
    condition: "FAIR",
    authenticityType: "ORIGINAL",
    city: "Санкт-Петербург",
    description:
      "Винтажная мембранная куртка с характером. Есть следы носки, молнии исправны.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT"],
    images: [
      { id: "p-015-1", url: img("photo-1503342217505-b0a15ec3261c"), alt: "Винтажная горная куртка" },
      { id: "p-015-2", url: img("photo-1529139574466-a303027c1d8b"), alt: "Техническая куртка" },
    ],
    popularityScore: 62,
    createdAt: "2026-06-23T10:00:00.000Z",
  },
  {
    id: "p-016",
    sellerId: "user-alina",
    shopId: "shop-luxe",
    title: "Gucci GG Wool Scarf",
    slug: "gucci-gg-wool-scarf",
    brand: "Gucci",
    category: "аксессуары",
    priceKopecks: 1550000,
    condition: "NEW_WITHOUT_TAGS",
    authenticityType: "ORIGINAL",
    city: "Казань",
    description:
      "Шарф без бирок, но без носки. Мягкая шерсть, рисунок ровный, края чистые.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT", "SAFE_DEAL"],
    images: [
      { id: "p-016-1", url: img("photo-1520903920243-00d872a2d1c9"), alt: "Шерстяной шарф Gucci" },
      { id: "p-016-2", url: img("photo-1516762689617-e1cffcef479d"), alt: "Аксессуар крупным планом" },
    ],
    popularityScore: 61,
    createdAt: "2026-06-22T10:00:00.000Z",
  },
  {
    id: "p-017",
    sellerId: "user-daniil",
    shopId: "shop-mono",
    title: "Rick Owens Berlin Sweatpants",
    slug: "rick-owens-berlin-sweatpants",
    brand: "Rick Owens",
    category: "брюки",
    clothingSize: "M",
    priceKopecks: 3400000,
    condition: "EXCELLENT",
    authenticityType: "ORIGINAL",
    city: "Москва",
    description:
      "Мягкие брюки Berlin, чистый черный цвет. Отличная база под длинные слои.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "SAFE_DEAL"],
    images: [
      { id: "p-017-1", url: img("photo-1473966968600-fa801b869a1a"), alt: "Черные брюки Rick Owens" },
      { id: "p-017-2", url: img("photo-1495385794356-15371f348c31"), alt: "Темный комплект" },
    ],
    popularityScore: 86,
    createdAt: "2026-06-21T10:00:00.000Z",
  },
  {
    id: "p-018",
    sellerId: "user-roma",
    shopId: "shop-sneaker",
    title: "Nike ACG Air Mowabb",
    slug: "nike-acg-air-mowabb",
    brand: "Nike",
    category: "кроссовки",
    shoeSize: "44",
    priceKopecks: 2200000,
    condition: "EXCELLENT",
    authenticityType: "ORIGINAL",
    city: "Новосибирск",
    description:
      "ACG-пара в спокойной палитре, подошва без критичного износа, комплект с коробкой.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT", "SAFE_DEAL"],
    images: [
      { id: "p-018-1", url: img("photo-1543508282-6319a3e2621f"), alt: "Nike ACG кроссовки" },
      { id: "p-018-2", url: img("photo-1542291026-7eec264c27ff"), alt: "Кроссовки на фоне" },
    ],
    popularityScore: 78,
    createdAt: "2026-06-20T10:00:00.000Z",
  },
  {
    id: "p-019",
    sellerId: "user-lera",
    title: "Moncler Logo Tee",
    slug: "moncler-logo-tee",
    brand: "Moncler",
    category: "футболки",
    clothingSize: "S",
    priceKopecks: 1450000,
    condition: "NEW_WITH_TAGS",
    authenticityType: "ORIGINAL",
    city: "Сочи",
    description:
      "Новая футболка с бирками, чистый белый цвет. Подойдет как аккуратная база.",
    status: "ACTIVE",
    dealMethods: ["DIRECT", "SAFE_DEAL"],
    images: [
      { id: "p-019-1", url: img("photo-1521572163474-6864f9cf17ab"), alt: "Футболка Moncler" },
      { id: "p-019-2", url: img("photo-1503341455253-b2e723bb3dbb"), alt: "Белая футболка" },
    ],
    popularityScore: 66,
    createdAt: "2026-06-19T10:00:00.000Z",
  },
  {
    id: "p-020",
    sellerId: "user-alina",
    shopId: "shop-lime",
    title: "Supreme Nylon Shoulder Bag",
    slug: "supreme-nylon-shoulder-bag",
    brand: "Supreme",
    category: "сумки",
    priceKopecks: 1180000,
    condition: "GOOD",
    authenticityType: "ORIGINAL",
    city: "Москва",
    description:
      "Небольшая сумка через плечо, молния исправна. Есть легкие следы носки на ремне.",
    status: "ACTIVE",
    dealMethods: ["PERSONAL_MEETING", "DIRECT"],
    images: [
      { id: "p-020-1", url: img("photo-1594223274512-ad4803739b7c"), alt: "Сумка через плечо Supreme" },
      { id: "p-020-2", url: img("photo-1606760227091-3dd870d97f1d"), alt: "Нейлоновая сумка" },
    ],
    popularityScore: 67,
    createdAt: "2026-06-18T10:00:00.000Z",
  },
];

export const reviews: Review[] = [
  {
    id: "review-001",
    authorId: "user-lera",
    targetShopId: "shop-asphalt",
    rating: 5,
    text: "Подробные фото, быстрая встреча, состояние совпало с описанием.",
    createdAt: "2026-06-30T10:00:00.000Z",
  },
  {
    id: "review-002",
    authorId: "user-roma",
    targetShopId: "shop-lime",
    rating: 5,
    text: "Приятный магазин, честно отметили мелкие следы носки на фурнитуре.",
    createdAt: "2026-06-28T10:00:00.000Z",
  },
  {
    id: "review-003",
    authorId: "user-alina",
    targetUserId: "user-daniil",
    productId: "p-018",
    rating: 5,
    text: "Все быстро, пара чистая, коробка и дополнительные фото были на месте.",
    createdAt: "2026-06-24T10:00:00.000Z",
  },
  {
    id: "review-004",
    authorId: "user-mark",
    targetUserId: "user-lera",
    rating: 4,
    text: "Хорошее описание, встретились в удобной точке. Хотелось бы больше фото бирок.",
    createdAt: "2026-06-20T10:00:00.000Z",
  },
  {
    id: "review-005",
    authorId: "user-daniil",
    targetShopId: "shop-sneaker",
    rating: 5,
    text: "Размер, состояние и комплектность совпали. Без лишних обещаний.",
    createdAt: "2026-06-18T10:00:00.000Z",
  },
];

export const deals: Deal[] = [
  {
    id: "deal-001",
    productId: "p-001",
    buyerId: "user-lera",
    sellerId: "user-mark",
    amountKopecks: 6800000,
    commissionPercent: 5,
    commissionAmountKopecks: 340000,
    method: "SAFE_DEAL",
    status: "AWAITING_PAYMENT",
    createdAt: "2026-07-08T10:00:00.000Z",
    updatedAt: "2026-07-08T12:00:00.000Z",
  },
  {
    id: "deal-002",
    productId: "p-003",
    buyerId: "user-alina",
    sellerId: "user-daniil",
    amountKopecks: 2450000,
    commissionPercent: 0,
    commissionAmountKopecks: 0,
    method: "PERSONAL_MEETING",
    status: "PENDING",
    createdAt: "2026-07-07T10:00:00.000Z",
    updatedAt: "2026-07-07T10:30:00.000Z",
  },
  {
    id: "deal-003",
    productId: "p-012",
    buyerId: "user-roma",
    sellerId: "user-mark",
    amountKopecks: 1390000,
    commissionPercent: 5,
    commissionAmountKopecks: 69500,
    method: "SAFE_DEAL",
    status: "DELIVERED",
    providerPaymentId: "provider-pending-id",
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-07-05T10:00:00.000Z",
  },
  {
    id: "deal-004",
    productId: "p-014",
    buyerId: "user-mark",
    sellerId: "user-lera",
    amountKopecks: 1250000,
    commissionPercent: 0,
    commissionAmountKopecks: 0,
    method: "DIRECT",
    status: "COMPLETED",
    createdAt: "2026-06-18T10:00:00.000Z",
    updatedAt: "2026-06-19T10:00:00.000Z",
  },
];

export function getUserById(id: string) {
  return users.find((user) => user.id === id);
}

export function getUserByUsername(username: string) {
  return users.find((user) => user.username === username);
}

export function getShopById(id?: string) {
  if (!id) {
    return undefined;
  }

  return shops.find((shop) => shop.id === id);
}

export function getShopBySlug(slug: string) {
  return shops.find((shop) => shop.slug === slug);
}

export function getProductById(id: string) {
  return products.find((product) => product.id === id);
}

export function getDealById(id: string) {
  return deals.find((deal) => deal.id === id);
}

export function getProductsByShop(shopId: string) {
  return products.filter((product) => product.shopId === shopId);
}

export function getProductsBySeller(userId: string) {
  return products.filter((product) => product.sellerId === userId);
}

export function getRelatedProducts(product: Product) {
  return products
    .filter(
      (item) =>
        item.id !== product.id &&
        (item.brand === product.brand || item.category === product.category),
    )
    .slice(0, 4);
}

export function getReviewsForShop(shopId: string) {
  return reviews.filter((review) => review.targetShopId === shopId);
}

export function getReviewsForUser(userId: string) {
  return reviews.filter((review) => review.targetUserId === userId);
}

export function getSellerForProduct(product: Product) {
  const shop = getShopById(product.shopId);
  const user = getUserById(product.sellerId);

  return {
    name: shop?.name ?? user?.displayName ?? "Продавец 88Shops",
    avatarUrl: shop?.avatarUrl ?? user?.avatarUrl,
    verified: shop?.verified ?? user?.verified ?? false,
    href: shop ? `/shops/${shop.slug}` : `/profile/${user?.username ?? "unknown"}`,
    rating: shop?.rating ?? user?.rating ?? 0,
    reviewsCount: shop?.reviewsCount ?? user?.reviewsCount ?? 0,
    salesCount: shop?.salesCount ?? user?.salesCount ?? 0,
  };
}
